# Generated by Django 6.0.4 on 2026-04-08 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolHomeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=2048)),
                ('game_id', models.PositiveIntegerField(unique=True)),
                ('game_date', models.DateField()),
                ('game_name', models.CharField(max_length=300)),
                ('tournament', models.CharField(max_length=200)),
                ('blue_champions', models.JSONField(default=list)),
                ('red_champions', models.JSONField(default=list)),
                ('raw', models.JSONField(default=dict)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-game_date', '-game_id'],
            },
        ),
    ]
