# Generated by Django 6.0.4 on 2026-04-08 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_golhomegame"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GolHomeGame",
            new_name="GolGame",
        ),
    ]

