# Generated by Django 6.0.4 on 2026-04-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_rename_golhomegame_golgame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
