# Generated by Django 6.0.4 on 2026-04-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_delete_listing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='golgame',
            options={'ordering': ['-match_date', '-match_id']},
        ),
        migrations.RenameField(
            model_name='golgame',
            old_name='game_date',
            new_name='match_date',
        ),
        migrations.RenameField(
            model_name='golgame',
            old_name='game_id',
            new_name='match_id',
        ),
        migrations.RenameField(
            model_name='golgame',
            old_name='game_name',
            new_name='match_name',
        ),
    ]
