# Generated by Django 6.0.4 on 2026-04-12 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_golgame_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameFullStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.PositiveIntegerField()),
                ('champion', models.CharField(max_length=200)),
                ('player', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kills', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deaths', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('assists', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cs', models.PositiveIntegerField(blank=True, null=True)),
                ('cs_in_team_jungle', models.PositiveIntegerField(blank=True, null=True)),
                ('cs_in_enemy_jungle', models.PositiveIntegerField(blank=True, null=True)),
                ('golds', models.PositiveIntegerField(blank=True, null=True)),
                ('gpm', models.PositiveIntegerField(blank=True, null=True)),
                ('vision_score', models.PositiveIntegerField(blank=True, null=True)),
                ('wards_placed', models.PositiveIntegerField(blank=True, null=True)),
                ('wards_destroyed', models.PositiveIntegerField(blank=True, null=True)),
                ('control_wards_purchased', models.PositiveIntegerField(blank=True, null=True)),
                ('detector_wards_placed', models.PositiveIntegerField(blank=True, null=True)),
                ('total_damage_to_champion', models.PositiveIntegerField(blank=True, null=True)),
                ('physical_damage', models.PositiveIntegerField(blank=True, null=True)),
                ('magic_damage', models.PositiveIntegerField(blank=True, null=True)),
                ('true_damage', models.PositiveIntegerField(blank=True, null=True)),
                ('dpm', models.PositiveIntegerField(blank=True, null=True)),
                ('solo_kills', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('double_kills', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('triple_kills', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quadra_kills', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('penta_kills', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gd_at_15', models.IntegerField(blank=True, null=True)),
                ('csd_at_15', models.IntegerField(blank=True, null=True)),
                ('xpd_at_15', models.IntegerField(blank=True, null=True)),
                ('lvld_at_15', models.IntegerField(blank=True, null=True)),
                ('objectives_stolen', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('damage_dealt_to_turrets', models.PositiveIntegerField(blank=True, null=True)),
                ('damage_dealt_to_buildings', models.PositiveIntegerField(blank=True, null=True)),
                ('total_heal', models.PositiveIntegerField(blank=True, null=True)),
                ('total_heals_on_teammates', models.PositiveIntegerField(blank=True, null=True)),
                ('damage_self_mitigated', models.PositiveIntegerField(blank=True, null=True)),
                ('total_damage_shielded_on_teammates', models.PositiveIntegerField(blank=True, null=True)),
                ('time_ccing_others', models.PositiveIntegerField(blank=True, null=True)),
                ('total_time_cc_dealt', models.PositiveIntegerField(blank=True, null=True)),
                ('total_damage_taken', models.PositiveIntegerField(blank=True, null=True)),
                ('total_time_spent_dead', models.PositiveIntegerField(blank=True, null=True)),
                ('consumables_purchased', models.PositiveIntegerField(blank=True, null=True)),
                ('items_purchased', models.PositiveIntegerField(blank=True, null=True)),
                ('shutdown_bounty_collected', models.IntegerField(blank=True, null=True)),
                ('shutdown_bounty_lost', models.IntegerField(blank=True, null=True)),
                ('kda', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('csm', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('gold_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('vspm', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('wpm', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('vwpm', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('wcpm', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('vs_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('dmg_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('ka_per_minute', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('kp_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('gol_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_full_stats', to='scraper.golgame')),
            ],
            options={
                'ordering': ['-gol_game_id', '-game_id', 'champion'],
                'indexes': [models.Index(fields=['gol_game', 'game_id'], name='scraper_gam_gol_gam_8d3579_idx'), models.Index(fields=['gol_game', 'kills'], name='scraper_gam_gol_gam_9e1943_idx'), models.Index(fields=['gol_game', 'deaths'], name='scraper_gam_gol_gam_2691c7_idx')],
                'constraints': [models.UniqueConstraint(fields=('gol_game', 'game_id', 'champion', 'player'), name='uniq_pick_full_stats_pick')],
            },
        ),
    ]
